### ISSUE TITLE
Create latest/stable channels for device, runner pip installs

### ISSUE THREAD

**Issue by pgdr** [FriskByBergen/python-friskby#24]
We will categorize devices into two classes
1. **stable** -- which runs normally, and every 24h (or rarer) does `pip install --upgrade friskby rpiparticle friskby-controlpanel`
2. **latest** --- which runs normally, but every hour (or at request) will run `pip install --upgrade friskby==0.0.beta`.

The versions `0.0.beta` will be used for unstable testing purposes; test upgrade functionality and normal running procedure.

When a beta version is deemed stable (all _latest_ devices are successfully upgraded and has run for days/weeks without fault), the beta version will be released as a new pip version.

We need to replace the `git version` in the server with two classes `latest` and `stable`, and update the config files, DeviceConfig and client/runner accordingly.

Ps., rename Runner to Client or `FriskbyUpdateManager` with executable service `fby_updater`?

**Comment by semafor** [comment]
> The versions 0.0.beta will be used for unstable testing purposes; test upgrade functionality and normal running procedure.

I don't think this will be very flexible. If `0.0.beta` is installed, it will not be installed again, effectively leaving us with one shot at a beta. Now, it seems `pip` comes with a [`--pre`](https://pip.pypa.io/en/stable/reference/pip_install/#pre-release-versions) switch, which will allow us to simply do `pip install --pre --upgrade`, which according to the docs, as well as this [so answer](http://stackoverflow.com/a/35131910/538866), will do the right thing: if version `0.8.2` was current, the `latest` devices would install `0.8.2.beta[0-9+]`—but `stable` devices would not consider the beta version since it could not be parsed as [`PEP426`](https://www.python.org/dev/peps/pep-0426/#abstract).
